### ISSUE TITLE
Passenger vs Puma

### ISSUE THREAD

**Issue by sauloperez** [codegram/decidim-deploy-heroku#8]
Hi! Is there a reason why we chose Passenger over other established app servers such as Puma or Unicorn?  Heroku [uses Puma](https://devcenter.heroku.com/articles/getting-started-with-rails5#configure-your-webserver) by default with Rails 5.x. I was wondering if this choice is because Decidim is not thread-safe or because simply the gem list hasn't been updated in a while.

**Comment by mrcasals** [comment]
Hi! I guess the gem list is outdated, we use Puma! Care to send a PR? 😄

**Comment by sauloperez** [comment]
aha! that's a green light then! I will send it ASAP.
